FROM ubuntu:16.04

SHELL ["/bin/bash", "-c"]

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-8-jdk python software-properties-common git-core gnupg flex bison gperf build-essential \
    zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
    lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache \
    libgl1-mesa-dev libxml2-utils xsltproc unzip mtools u-boot-tools \
    htop iotop sysstat iftop pigz bc device-tree-compiler lunzip \
    dosfstools rsync

RUN DEBIAN_FRONTEND=noninteractive apt update && \
	DEBIAN_FRONTEND=noninteractive apt install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev liblzma-dev git && \
	curl -L https://www.openssl.org/source/openssl-1.1.1q.tar.gz | (cd /usr/src; tar xz) ; \
	cd /usr/src/openssl-1.1.1q && ./config --prefix=/usr/local && make -j4 && make install && \
	curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash ; \
	echo >> /root/.bashrc && \
	echo 'export PATH="/root/.pyenv/bin:$PATH"' >> /root/.bashrc && \
	echo 'eval "$(pyenv init -)"' >> /root/.bashrc && \
	echo 'eval "$(pyenv virtualenv-init -)"' >> /root/.bashrc && \
	source /root/.bashrc && \
	CONFIGURE_OPTS="--with-openssl=/usr/local --with-openssl-rpath=auto" pyenv install 3.10.5 && \
	pyenv global 3.10.5

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y {g++,gcc}-4.9-aarch64-linux-gnu {g++,gcc}-4.7-arm-linux-gnueabihf

RUN curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo && \
    chmod +x /usr/local/bin/repo

RUN curl -L https://github.com/aktau/github-release/releases/download/v0.6.2/linux-amd64-github-release.tar.bz2 | tar -C /tmp -jx && \
    mv /tmp/bin/linux/amd64/github-release /usr/local/bin/

RUN which repo && \
    which github-release

COPY build.sh /root/
RUN chmod +x /root/build.sh

COPY init-repo-android7-Copy.sh /root/init-repo-android7.sh
RUN chmod +x /root/init-repo-android7.sh

COPY fixedDefaultManifestsAndroid7.xml /root/

COPY fixedLibcedarcConfig.mk /root/

COPY fixGitConfigAndroid7OpengapsSourceArm64 /root/

COPY fixGitConfigAndroid7OpengapsSourceArm /root/

COPY fixGitConfigAndroid7OpengapsSourceAll /root/

COPY Jenkinsfile /root/

RUN git config --global user.email "docker_build@inx-systems.com" && \
    git config --global user.name "INX Limited"

RUN build_deps="curl" && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ${build_deps} ca-certificates && \
    curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git-lfs && \
    git lfs install && \
    rm -r /var/lib/apt/lists/* && \
    sed -i 's/TLSv1, TLSv1.1, //g' /etc/java-8-openjdk/security/java.security
